openapi: 3.0.3
info:
  title: Patient Service v1
  description: |-
    API for Patient Service
  termsOfService: http://swagger.io/terms/
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io